services:
  - type: web
    name: radar-parser
    runtime: node
    buildCommand: |
      npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
