services:
  - type: web
    name: radar-parser
    runtime: node
    buildCommand: |
      rm -rf .cache
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "24"
